application: test-likelion-syg #Your_Application_id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Application Webpage icon
# - url: /favicon.ico
#   static_files: application/static/res/img/favicon.ico
#   upload: application/static/res/img/favicon.ico

# [application/static/*] => [project-id.appspot.com/static/*]
- url: static
  static_dir: application/static

# application[directory name] : module name
- url: .*
  script: application.app

# Following Libraries don't have to be included in 'lib'
libraries:
- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"
